In [6]:
import pandas as pd;
df = pd.read_csv("data/Combined_dataset.csv");
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

Head() - shows top 5 rows

In [9]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

Tail() - shows bottom 5 rows

In [8]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

Check shape - (rows & column)

In [10]:
df.shape

(1000, 24)

View Column Names

In [11]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

Check datatypes

In [12]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

Handling Missing Values

In [13]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [15]:
df[["discount"]]

     discount
0        58.0
1        35.0
2        65.0
3        52.0
4        17.0
..        ...
995      50.0
996      45.0
997      50.0
998      20.0
999      31.0

[1000 rows x 1 columns]

In [17]:
df["discount"] = df["discount"].fillna(df["discount"].mean())
df["discount"]

0      58.0
1      35.0
2      65.0
3      52.0
4      17.0
       ...
995    50.0
996    45.0
997    50.0
998    20.0
999    31.0
Name: discount, Length: 1000, dtype: float64

In [18]:
df["what_customers_said"]

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
995    NaN
996    NaN
997    NaN
998    NaN
999    NaN
Name: what_customers_said, Length: 1000, dtype: str

In [20]:
df["what_customers_said"] = df["what_customers_said"].fillna("No Review");
df["what_customers_said"]

0      No Review
1      No Review
2      No Review
3      No Review
4      No Review
         ...
995    No Review
996    No Review
997    No Review
998    No Review
999    No Review
Name: what_customers_said, Length: 1000, dtype: str

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                1000 non-null   float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     1000 non-null   str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [22]:
df["seller_name"]

0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
            ...
995               NaN
996               NaN
997               NaN
998    Tru███m R███il
999               NaN
Name: seller_name, Length: 1000, dtype: str

In [24]:
df["seller_name"] = df["seller_name"].fillna("Unknown Seller")
df["seller_name"]

0      Unknown Seller
1      Unknown Seller
2      Unknown Seller
3      Unknown Seller
4      Unknown Seller
            ...
995    Unknown Seller
996    Unknown Seller
997    Unknown Seller
998    Tru███m R███il
999    Unknown Seller
Name: seller_name, Length: 1000, dtype: str

In [25]:
df["videos"]

0                                  ["rw-8376765_cae700"]
1                                  ["rw-9136281_cae700"]
2      ["https://videos.myntassets.com/assets/videos/...
3      ["https://videos.myntassets.com/assets/videos/...
4                                                    NaN
                             ...
995                                      ["pi-13698258"]
996    ["rw-16896006_cae700","https://videos.myntasse...
997                                                  NaN
998                                                  NaN
999                                                  NaN
Name: videos, Length: 1000, dtype: str

In [26]:
df["videos"] = df["videos"].fillna("Unknown")

In [27]:
df["videos"]

0                                  ["rw-8376765_cae700"]
1                                  ["rw-9136281_cae700"]
2      ["https://videos.myntassets.com/assets/videos/...
3      ["https://videos.myntassets.com/assets/videos/...
4                                                Unknown
                             ...
995                                      ["pi-13698258"]
996    ["rw-16896006_cae700","https://videos.myntasse...
997                                              Unknown
998                                              Unknown
999                                              Unknown
Name: videos, Length: 1000, dtype: str

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                1000 non-null   float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     1000 non-null   str
 16  seller_name             1000 non-null   str
 17  sizes                   1000 non-null   str
 18  videos                  1000 non-null   str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [29]:
df["variations"]

0                                             [{}]
1                                          [{},{}]
2                              [{},{},{},{},{},{}]
3                                              NaN
4      [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
                          ...
995                                            NaN
996                                            NaN
997                      [{},{},{},{},{},{},{},{}]
998                                            NaN
999                                  [{},{},{},{}]
Name: variations, Length: 1000, dtype: str

In [30]:
df["variations"] = df["variations"].fillna("[{}]")

In [31]:
df["variations"]

0                                             [{}]
1                                          [{},{}]
2                              [{},{},{},{},{},{}]
3                                             [{}]
4      [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
                          ...
995                                           [{}]
996                                           [{}]
997                      [{},{},{},{},{},{},{},{}]
998                                           [{}]
999                                  [{},{},{},{}]
Name: variations, Length: 1000, dtype: str

In [32]:
df["seller_information"]

0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
                             ...
995                                                  NaN
996                                                  NaN
997                                                  NaN
998    Sho███o. ███-10█████████enu███████████████████...
999                                                  NaN
Name: seller_information, Length: 1000, dtype: str

In [33]:
df["seller_information"] = df["seller_information"].fillna("no information known")

In [34]:
df["seller_information"]

0                                   no information known
1                                   no information known
2                                   no information known
3                                   no information known
4                                   no information known
                             ...
995                                 no information known
996                                 no information known
997                                 no information known
998    Sho███o. ███-10█████████enu███████████████████...
999                                 no information known
Name: seller_information, Length: 1000, dtype: str

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                1000 non-null   float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     1000 non-null   str
 16  seller_name             1000 non-null   str
 17  sizes                   1000 non-null   str
 18  videos                  1000 non-null   str
 19  seller_information      1000 non-null   str
 20  variations              1000 non-null   str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [36]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",no information known,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Review,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,no information known,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Unknown,no information known,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,Tru███m R███il,"[{""size"":""Onesize""}]",Unknown,Sho███o. ███-10█████████enu███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",No Review,Unknown Seller,"[{""size"":""Medium""}]",Unknown,no information known,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

Basic Operations

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                1000 non-null   float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     1000 non-null   str
 16  seller_name             1000 non-null   str
 17  sizes                   1000 non-null   str
 18  videos                  1000 non-null   str
 19  seller_information      1000 non-null   str
 20  variations              1000 non-null   str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

Select Columns

In [39]:
df[["product_id","title", "product_description", "final_price", "amount_of_stars"]].head()

,product_id,title,product_description,final_price,amount_of_stars
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,"""₹3,995.00""","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":..."
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,"""₹2,899.00""","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":..."
2,17633752,Lavie,Aries Women Pink Mini Backpack,"""₹2,999.00""","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""..."
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,"""₹1,675.00""","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star..."
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,"""₹2,899.00""","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":..."

In [41]:
df[["product_id", "title", "product_details", "seller_name", "category"]].head(50)

,product_id,title,product_details,seller_name,category
0,8376765,Lino Perros,"{""description"":""Navy Blue solid backpackNon-Pa...",Unknown Seller,backpacks
1,9136281,Tommy Hilfiger,"{""description"":""Navy Blue backpackNon-Padded h...",Unknown Seller,backpacks
2,17633752,Lavie,"{""description"":""Pink solid backpacks Non-padd...",Unknown Seller,backpacks
3,1376949,F Gear,"{""description"":""Navy and grey printed backpack...",Unknown Seller,backpacks
4,13939916,MYTRIDENT,"{""description"":""Blue solid bath robe, has a sh...",Unknown Seller,bath-robe
5,17198778,H&M,"{""description"":""Soap dispenser in glazed stone...",H &███Hen███ & █████████eta█████████████████████,bathroom-accessories
6,19851824,AVI Living,"{""description"":""Set content: 1 Bath TowelFeatu...",Unknown Seller,bath-towels
7,18602872,My Room,"{""description"":""Set content: 1 king bedsheet w...",Unknown Seller,bedsheets
8,18602850,My Room,"{""description"":""Dimensions: Super King bedshee...",Unknown Seller,bedsheets
9,8961147,Story@home,"{""description"":""Set content: 1 King bedsheet w...",Unknown Seller,bedsheets
10,8430275,MYTRIDENT,"{""description"":""Set content: 1 Queen bedsheet ...",Unknown Seller,bedsheets
11,18346118,Arrabi,"{""description"":""Set Content: 1 King Bedsheet w...",Sig███Ove███as,bedsheets
12,18327434,BELLA CASA,"{""description"":""WHAT YOU GET : 1 Double Bedshe...",Bel███Cas███ash█████████ail█████████,bedsheets
13,18492504,ROMEE,"{""description"":""Set content: 1 king bedsheet w...",Unknown Seller,bedsheets
14,13729978,DDecor,"{""description"":""Set content: 1 King bedsheet w...",Unknown Seller,bedsheets
15,19788630,Home Ecstasy,"{""description"":""140tc 100% Cotton Printed Teal...",Unknown Seller,bedsheets
16,20296382,DREAM WEAVERZ,"{""description"":""Set Content : 1 King bedsheet ...",Unknown Seller,bedsheets
17,18346134,Arrabi,"{""description"":""Set content: 1 king bedsheet w...",Unknown Seller,bedsheets
18,22409156,Kastner,"{""description"":""Brown textured synthetic leath...",Kas███r L███her█████████Pvt██████,belts
19,18985918,Tommy Hilfiger,"{""description"":""Navy blue embroidered bodysuit...",PVH███VIN███ASH█████████TE ███████████████,bodysuit
20,22120138,Ed-a-Mamma Baby,"{""description"":""Pack of 2 printed body suits i...",ETE███LIA███EAT█████████CHA███████████████████...,bodysuit
21,1728397,Mactree,"{""description"":""A pair of round-toe brown? fla...",MAX███ IN███NAT██████,boots
22,21427828,London Rag,"{""description"":""A pair of solid knee length wi...",VOL███FAS███N P█████████,boots
23,17372928,The Souled Store,"{""description"":""Blue, white and black printed ...",THE███ULE███TOR█████████D.,boxers
24,15115018,Jockey,"{""description"":""Grey melange knitted sports br...",Tru███m R███il,bra
25,22063882,GROVERSONS Paris Beauty,"{""description"":""An edgier take on a basic styl...",Gro███son███ppa█████████Ltd███,bra
26,19219450,Susie,"{""description"":""An edgier take on a basic styl...",GEN███AD ███AIL█████████LIM██████,bra
27,22196924,Zivame,"{""description"":""Features:VANumber: zi102dfasha...",MIL███AR ███AIL█████████LIM██████,bra
28,19219468,Susie,"{""description"":""Designed to lend the right sha...",GEN███AD ███AIL█████████LIM██████,bra
29,22278620,Tweens,"{""description"":""Get the right kind of support ...",Bel███Lin███ies█████████.,bra
30,19277544,Marks & Spencer,"{""description"":""Bring home this ultra-soft bra...",Ret███Net███,bra
31,18223842,max,"{""description"":""Bring home this ultra-soft bra...",Unknown Seller,bra
32,18656766,VStar,"{""description"":""You'll always prefer to pick t...",V S███ CR███ION█████████,bra
33,18656764,VStar,"{""description"":""This padded and non-wired cott...",V S███ CR███ION█████████,bra
34,13523458,shyaway,"{""description"":""Multicoloured printed full-cov...",Unknown Seller,bra
35,18652628,max,"{""description"":""Designed to give you sheer com...",Unknown Seller,bra
36,17774350,Zivame,"{""description"":""Make an interesting and drool-...",Unknown Seller,bra
37,16704504,ZINU,"{""description"":""Silver-toned charm bracelet M...",SAN███UNE███,bracelet
38,21873792,KARATCART,"{""description"":""Silver-toned and blue handcraf...",KOK███V G███AL █████████,bracelet
39,21573578,Jewels Galaxy,"{""description"":""Bangle-style braceletMaterial ...",RS ███els███,bracelet
40,18100576,MINUTIAE,"{""description"":""Gold-toned and white handcraft...",Unknown Seller,bracelet
41,18532334,Pepe Jeans,"{""description"":""Made of ultra-soft premium enr...",Vis███ St███,briefs
42,16696094,Van Heusen,"{""description"":""Black solid mid-rise briefs, h...",Wes███ry ███din█████████d_M██████,briefs
43,21867416,DressBerry,"{""description"":""Peach-coloured solid boy short...",VAC███CRE███ONS███,briefs
44,21850852,Soie,"{""description"":""PRODUCT DETAILS : Our most com...",GIN███IND███RIE█████████,briefs
45,21860658,EROTISSCH,"{""description"":""Blue printed laced basic brief...",AAK███INT███TES█████████LIM██████,briefs
46,21569986,Chromozome,"{""description"":""Pack of 4 Premium Briefs for M...",Sup███om ███,briefs
47,19206416,ABELINO,"{""description"":""Pack of 3 High Rise Assorted B...",ARI███T T███ING█████████,briefs
48,22196594,Zoiro,"{""description"":""Pack of two blue adn grey soli...",J.G███OSI███ PR█████████ITE███,briefs
49,22196914,Zivame,"{""description"":""Pack of 3 bikini briefsRed pri...",MIL███AR ███AIL█████████LIM██████,briefs

2.Filter

In [43]:
df[df["rating"] > 4.0]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.000000,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",no information known,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.000000,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Review,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.000000,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.000000,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,no information known,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,53.503982,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",Unknown,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.000000,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",No Review,DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.000000,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.000000,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.000000,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.000000,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,Tru███m R███il,"[{""size"":""Onesize""}]",Unknown,Sho███o. ███-10█████████enu███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

In [44]:
df[(df["rating"] > 2.5) & (df["rating"] <= 4.0)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Unknown,no information known,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
9,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Double King""}]",Unknown,no information known,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
13,18492504,ROMEE,Blue & Beige Conversational 160 TC King Bedshe...,3.9,10,3499,65.0,"""₹3,499.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Double King""}]",Unknown,no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
14,13729978,DDecor,White & Brown Floral 350 TC Cotton 1 King Beds...,3.6,15,1599,20.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Double King""}]",Unknown,no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,9053317,TIMESMITH,Men Black Analogue Watch TSC-008,3.7,304,2499,88.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/905...,...,"{""1_star"":54,""2_stars"":20,""3_stars"":34,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9053317_cae700"",""https://videos.myntasset...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
993,19322504,V2A,Girls Blue Printed Dial & Pink Straps Digital ...,4.0,6,1599,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,Br ███erp███es,"[{""size"":""Onesize""}]",Unknown,Kha███ no███122█████████lhi██████████████████,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Unknown,no information known,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",No Review,Unknown Seller,"[{""size"":""Medium""}]",Unknown,no information known,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [45]:
df[["final_price"]]

      final_price
0     "₹3,995.00"
1     "₹2,899.00"
2     "₹2,999.00"
3     "₹1,675.00"
4     "₹2,899.00"
..            ...
995  "₹11,890.00"
996   "₹8,900.00"
997   "₹7,950.00"
998   "₹2,636.00"
999     "₹699.00"

[1000 rows x 1 columns]

In [46]:
df["final_price"] = df["final_price"].str.replace("₹", "")
df["final_price"] = df["final_price"].str.replace(",", "")
df["final_price"]

0       "3995.00"
1       "2899.00"
2       "2999.00"
3       "1675.00"
4       "2899.00"
          ...
995    "11890.00"
996     "8900.00"
997     "7950.00"
998     "2636.00"
999      "699.00"
Name: final_price, Length: 1000, dtype: str

In [47]:
df["final_price"] = df["final_price"].str.replace('"', "")
df["final_price"]

0       3995.00
1       2899.00
2       2999.00
3       1675.00
4       2899.00
         ...
995    11890.00
996     8900.00
997     7950.00
998     2636.00
999      699.00
Name: final_price, Length: 1000, dtype: str

In [48]:
df["final_price"] = df['final_price'].astype(float)

In [49]:
df["final_price"]

0       3995.0
1       2899.0
2       2999.0
3       1675.0
4       2899.0
        ...
995    11890.0
996     8900.0
997     7950.0
998     2636.0
999      699.0
Name: final_price, Length: 1000, dtype: float64

In [50]:
df[df["final_price"] > 1500.0]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",no information known,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Review,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,no information known,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,6250.0,INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Unknown,no information known,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,Tru███m R███il,"[{""size"":""Onesize""}]",Unknown,Sho███o. ███-10█████████enu███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

Remove Duplicates

In [51]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",no information known,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Review,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,no information known,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Unknown Seller,"[{""size"":""Onesize""}]",Unknown,no information known,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,Tru███m R███il,"[{""size"":""Onesize""}]",Unknown,Sho███o. ███-10█████████enu███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699.0,INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",No Review,Unknown Seller,"[{""size"":""Medium""}]",Unknown,no information known,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [54]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [55]:
df.duplicated().sum()

np.int64(0)

No duplicates found

Creating a derived column

In [56]:
df["quantity"] = 2;
df["total_amount"] = df["final_price"] * df["quantity"]
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2,7990.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",no information known,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2,5798.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2,5998.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2,3350.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,no information known,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,2,5798.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,2,23780.0
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,2,17800.0
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,Unknown Seller,"[{""size"":""Onesize""}]",Unknown,no information known,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,2,15900.0
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,Tru███m R███il,"[{""size"":""Onesize""}]",Unknown,Sho███o. ███-10█████████enu███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,2,5272.0
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699.0,INR,http://assets.myntassets.com/assets/images/186...,...,Unknown Seller,"[{""size"":""Medium""}]",Unknown,no information known,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,2,1398.0

In [58]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2,7990.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",no information known,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2,5798.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2,5998.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,2,3350.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,no information known,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,2,5798.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,2,23780.0
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",no information known,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,2,17800.0
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,Unknown Seller,"[{""size"":""Onesize""}]",Unknown,no information known,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,2,15900.0
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,Tru███m R███il,"[{""size"":""Onesize""}]",Unknown,Sho███o. ███-10█████████enu███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,2,5272.0
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699.0,INR,http://assets.myntassets.com/assets/images/186...,...,Unknown Seller,"[{""size"":""Medium""}]",Unknown,no information known,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,2,1398.0

In [59]:
df.to_csv("Combined_cleaned_dataset.csv", index=False)