In [4]:
from tokenize import String

import pandas as pd
from jupyter_core.migrate import regex

df = pd.read_csv("data/ethnic-dresses.csv")
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21604464,Inddus,Pink Sheer Floral Embroidered Midi Ethnic Dres...,3.3,7,6299.0,58.0,"""₹2,645.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Nat███l L███sty█████████ts ██████████████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,4-B███nja███Tow█████████oin███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
1,21990058,Rustorange,Floral Printed A-Line Midi Ethnic Dress,5.0,2,3299.0,55.0,"""₹1,484.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Zak███i I███tec█████████ Li██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",NaN,1st███oor███ - █████████R -███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
2,21992820,PANIT,Embroidered Sequinned Georgette Fit And Flare ...,4.4,14,7999.0,71.0,"""₹2,319.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,R.U███NGH███D G█████████PPA█████████████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,G-6███Gro███ fl█████████-6N███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
3,15741084,Ashnaina,Red Floral Crepe Tiered Maxi Dress,3.2,6,1799.0,65.0,"""₹629.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,B-1███ OK███ IN█████████ASE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
4,15741088,Ashnaina,Women Brown Animal Midi Fit and Flare Dress,4.1,88,1799.0,67.0,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":12,""4_stars""...",NaN,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,B-1███ OK███ IN█████████ASE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
5,15788632,AURELIA,Black Checked Empire Midi Dress,4.2,14,2499.0,44.0,"""₹1,380.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",NaN,Vil███e B███a B█████████ata███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
6,15749780,W,Women Mustard Yellow & White Ethnic Printed Ma...,4.3,23,3999.0,60.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Fla███ech███tai███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",NaN,"3rd███165███th █████████, s███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
7,16197802,Vishudh,Grey Floral Embroidered Ethnic Maxi Dress,3.9,609,3049.0,60.0,"""₹853.00""",INR,http://assets.myntassets.com/assets/images/161...,...,"{""1_star"":77,""2_stars"":36,""3_stars"":56,""4_star...",NaN,Fla███tar███mme██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,"1st███oor███abi█████████02,███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
8,19197596,W,Blue Floral Chiffon A-Line Midi Dress,3.9,10,2799.0,49.0,"""₹1,420.00""",INR,http://assets.myntassets.com/assets/images/191...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",NaN,Vil███e B███a B█████████ata███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
9,18922226,Ahalyaa,Off White Geometric Printed Maxi Dress,2.8,8,4300.0,63.0,"""₹1,591.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,UDA███ASH███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,1ST███OOR███D 2█████████ PL███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
10,22411344,Juniper,Floral Embroidered Flared Cotton Midi Dress,3.9,11,4149.0,75.0,"""₹1,037.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,AMA███XPO███ IN█████████AL █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""To...",NaN,G-9███SIT███RA █████████L A███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
11,19990734,VASTRAMAY,Girls Mustard Yellow Chikankari Cotton Ethnic ...,4.7,9,2499.0,61.0,"""₹974.00""",INR,http://assets.myntassets.com/assets/images/199...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Vas███may███t. ██████,"[{""size"":""2-3Y"",""value"":""9.5in"",""value_name"":""...","[""rw-19990734_cae700""]",59A███ATH███AR █████████Kol███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
12,10127829,Geroo Jaipur,White & Red Floral Hand Block Printed Pure Cot...,3.8,6,2499.0,60.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,ITS███FFE███T,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""T...",NaN,21-███gal███har█████████l P███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
13,10132319,Karmic Vision,Women Grey & Red Solid Maxi Dress,3.9,12,4999.0,53.0,"""₹2,349.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,V S███ERS███,"[{""size"":""S"",""value"":""34.5in"",""value_name"":""To...",NaN,F-6███Ary███ama█████████hi ██████████████████,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
14,13404948,YASH GALLERY,Women Black & White Cotton Printed A-Line Mate...,4.1,67,3899.0,76.0,"""₹935.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":5,""3_stars"":8,""4_stars"":...",NaN,Yas███all███ Pr█████████ite███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,B-6███RO.███. 6█████████SIK███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
15,12994772,Souchii,Women Cream-Coloured Floral Printed A-Line Dress,3.9,10,1999.0,47.0,"""₹1,059.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,MOH███BHO███AMU█████████ATE█████████,"[{""size"":""S"",""value"":""42.0in"",""value_name"":""Fr...",NaN,"no-███, G███ama█████████, b███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
16,13355452,Rangriti,Women Coral Pink & White Liva Checked A-Line D...,4.4,33,1299.0,35.0,"""₹1,299.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":3,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Fr...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
17,13405888,Saanjh,Women Green Printed Fit and Flare Dress,4.0,7,1969.0,62.0,"""₹787.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,SHA███ RE███LS,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,C 5███ RR███NEX█████████BEH███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
18,22603284,JAIPURI COLLECTION,Ethnic Motifs Printed Maxi Ethnic Dress,3.9,10,2899.0,71.0,"""₹840.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Jai███i C███ect██████,"[{""size"":""M"",""value"":""52.0in"",""value_name"":""Fr...",NaN,"46,███ini███lon█████████erJ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
19,22583702,Mialo fashion,Ethnic Printed Kaftan Dress,2.7,9,2999.0,78.0,"""₹659.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,MIA███FAS███N,"[{""size"":""S"",""value"":""46.0in"",""value_name"":""Fr...",NaN,11/███ Ka███i P█████████aro███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses

In [5]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21604464,Inddus,Pink Sheer Floral Embroidered Midi Ethnic Dres...,3.3,7,6299.0,58.0,"""₹2,645.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Nat███l L███sty█████████ts ██████████████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,4-B███nja███Tow█████████oin███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
1,21990058,Rustorange,Floral Printed A-Line Midi Ethnic Dress,5.0,2,3299.0,55.0,"""₹1,484.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Zak███i I███tec█████████ Li██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",NaN,1st███oor███ - █████████R -███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
2,21992820,PANIT,Embroidered Sequinned Georgette Fit And Flare ...,4.4,14,7999.0,71.0,"""₹2,319.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,R.U███NGH███D G█████████PPA█████████████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,G-6███Gro███ fl█████████-6N███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
3,15741084,Ashnaina,Red Floral Crepe Tiered Maxi Dress,3.2,6,1799.0,65.0,"""₹629.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,B-1███ OK███ IN█████████ASE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
4,15741088,Ashnaina,Women Brown Animal Midi Fit and Flare Dress,4.1,88,1799.0,67.0,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":12,""4_stars""...",NaN,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,B-1███ OK███ IN█████████ASE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses

In [6]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
15,12994772,Souchii,Women Cream-Coloured Floral Printed A-Line Dress,3.9,10,1999.0,47.0,"""₹1,059.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,MOH███BHO███AMU█████████ATE█████████,"[{""size"":""S"",""value"":""42.0in"",""value_name"":""Fr...",NaN,"no-███, G███ama█████████, b███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
16,13355452,Rangriti,Women Coral Pink & White Liva Checked A-Line D...,4.4,33,1299.0,35.0,"""₹1,299.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":3,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Fr...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
17,13405888,Saanjh,Women Green Printed Fit and Flare Dress,4.0,7,1969.0,62.0,"""₹787.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,SHA███ RE███LS,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,C 5███ RR███NEX█████████BEH███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
18,22603284,JAIPURI COLLECTION,Ethnic Motifs Printed Maxi Ethnic Dress,3.9,10,2899.0,71.0,"""₹840.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Jai███i C███ect██████,"[{""size"":""M"",""value"":""52.0in"",""value_name"":""Fr...",NaN,"46,███ini███lon█████████erJ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
19,22583702,Mialo fashion,Ethnic Printed Kaftan Dress,2.7,9,2999.0,78.0,"""₹659.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,MIA███FAS███N,"[{""size"":""S"",""value"":""46.0in"",""value_name"":""Fr...",NaN,11/███ Ka███i P█████████aro███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses

Check Shape (rows & column)

In [7]:
df.shape

(20, 24)

View Column Names

In [8]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

Check DataTypes

In [9]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said       float64
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

Handling Missing Values

In [10]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21604464,Inddus,Pink Sheer Floral Embroidered Midi Ethnic Dres...,3.3,7,6299.0,58.0,"""₹2,645.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Nat███l L███sty█████████ts ██████████████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,4-B███nja███Tow█████████oin███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
1,21990058,Rustorange,Floral Printed A-Line Midi Ethnic Dress,5.0,2,3299.0,55.0,"""₹1,484.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Zak███i I███tec█████████ Li██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",NaN,1st███oor███ - █████████R -███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
2,21992820,PANIT,Embroidered Sequinned Georgette Fit And Flare ...,4.4,14,7999.0,71.0,"""₹2,319.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",NaN,R.U███NGH███D G█████████PPA█████████████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,G-6███Gro███ fl█████████-6N███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
3,15741084,Ashnaina,Red Floral Crepe Tiered Maxi Dress,3.2,6,1799.0,65.0,"""₹629.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,B-1███ OK███ IN█████████ASE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
4,15741088,Ashnaina,Women Brown Animal Midi Fit and Flare Dress,4.1,88,1799.0,67.0,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":12,""4_stars""...",NaN,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,B-1███ OK███ IN█████████ASE███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
5,15788632,AURELIA,Black Checked Empire Midi Dress,4.2,14,2499.0,44.0,"""₹1,380.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",NaN,Vil███e B███a B█████████ata███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
6,15749780,W,Women Mustard Yellow & White Ethnic Printed Ma...,4.3,23,3999.0,60.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Fla███ech███tai███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",NaN,"3rd███165███th █████████, s███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
7,16197802,Vishudh,Grey Floral Embroidered Ethnic Maxi Dress,3.9,609,3049.0,60.0,"""₹853.00""",INR,http://assets.myntassets.com/assets/images/161...,...,"{""1_star"":77,""2_stars"":36,""3_stars"":56,""4_star...",NaN,Fla███tar███mme██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,"1st███oor███abi█████████02,███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
8,19197596,W,Blue Floral Chiffon A-Line Midi Dress,3.9,10,2799.0,49.0,"""₹1,420.00""",INR,http://assets.myntassets.com/assets/images/191...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",NaN,Vil███e B███a B█████████ata███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
9,18922226,Ahalyaa,Off White Geometric Printed Maxi Dress,2.8,8,4300.0,63.0,"""₹1,591.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,UDA███ASH███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,1ST███OOR███D 2█████████ PL███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
10,22411344,Juniper,Floral Embroidered Flared Cotton Midi Dress,3.9,11,4149.0,75.0,"""₹1,037.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,AMA███XPO███ IN█████████AL █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""To...",NaN,G-9███SIT███RA █████████L A███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
11,19990734,VASTRAMAY,Girls Mustard Yellow Chikankari Cotton Ethnic ...,4.7,9,2499.0,61.0,"""₹974.00""",INR,http://assets.myntassets.com/assets/images/199...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Vas███may███t. ██████,"[{""size"":""2-3Y"",""value"":""9.5in"",""value_name"":""...","[""rw-19990734_cae700""]",59A███ATH███AR █████████Kol███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
12,10127829,Geroo Jaipur,White & Red Floral Hand Block Printed Pure Cot...,3.8,6,2499.0,60.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,ITS███FFE███T,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""T...",NaN,21-███gal███har█████████l P███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
13,10132319,Karmic Vision,Women Grey & Red Solid Maxi Dress,3.9,12,4999.0,53.0,"""₹2,349.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,V S███ERS███,"[{""size"":""S"",""value"":""34.5in"",""value_name"":""To...",NaN,F-6███Ary███ama█████████hi ██████████████████,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
14,13404948,YASH GALLERY,Women Black & White Cotton Printed A-Line Mate...,4.1,67,3899.0,76.0,"""₹935.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":5,""3_stars"":8,""4_stars"":...",NaN,Yas███all███ Pr█████████ite███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",NaN,B-6███RO.███. 6█████████SIK███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
15,12994772,Souchii,Women Cream-Coloured Floral Printed A-Line Dress,3.9,10,1999.0,47.0,"""₹1,059.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,MOH███BHO███AMU█████████ATE█████████,"[{""size"":""S"",""value"":""42.0in"",""value_name"":""Fr...",NaN,"no-███, G███ama█████████, b███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
16,13355452,Rangriti,Women Coral Pink & White Liva Checked A-Line D...,4.4,33,1299.0,35.0,"""₹1,299.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":3,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Fr...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
17,13405888,Saanjh,Women Green Printed Fit and Flare Dress,4.0,7,1969.0,62.0,"""₹787.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,SHA███ RE███LS,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,C 5███ RR███NEX█████████BEH███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
18,22603284,JAIPURI COLLECTION,Ethnic Motifs Printed Maxi Ethnic Dress,3.9,10,2899.0,71.0,"""₹840.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Jai███i C███ect██████,"[{""size"":""M"",""value"":""52.0in"",""value_name"":""Fr...",NaN,"46,███ini███lon█████████erJ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
19,22583702,Mialo fashion,Ethnic Printed Kaftan Dress,2.7,9,2999.0,78.0,"""₹659.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,MIA███FAS███N,"[{""size"":""S"",""value"":""46.0in"",""value_name"":""Fr...",NaN,11/███ Ka███i P█████████aro███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses

In [11]:
print(df.isnull())

    product_id  title  product_description  rating  ratings_count  \
0        False  False                False   False          False
1        False  False                False   False          False
2        False  False                False   False          False
3        False  False                False   False          False
4        False  False                False   False          False
5        False  False                False   False          False
6        False  False                False   False          False
7        False  False                False   False          False
8        False  False                False   False          False
9        False  False                False   False          False
10       False  False                False   False          False
11       False  False                False   False          False
12       False  False                False   False          False
13       False  False                False   False          False
14       False  False                False   False          False
15       False  False                False   False          False
16       False  False                False   False          False
17       False  False                False   False          False
18       False  False                False   False          False
19       False  False                False   False          False

    initial_price  discount  final_price  currency  images  ...  \
0           False     False        False     False   False  ...
1           False     False        False     False   False  ...
2           False     False        False     False   False  ...
3           False     False        False     False   False  ...
4           False     False        False     False   False  ...
5           False     False        False     False   False  ...
6           False     False        False     False   False  ...
7           False     False        False     False   False  ...
8           False     False        False     False   False  ...
9           False     False        False     False   False  ...
10          False     False        False     False   False  ...
11          False     False        False     False   False  ...
12          False     False        False     False   False  ...
13          False     False        False     False   False  ...
14          False     False        False     False   False  ...
15          False     False        False     False   False  ...
16          False     False        False     False   False  ...
17          False     False        False     False   False  ...
18          False     False        False     False   False  ...
19          False     False        False     False   False  ...

    amount_of_stars  what_customers_said  seller_name  sizes  videos  \
0             False                 True        False  False    True
1             False                 True        False  False    True
2             False                 True        False  False    True
3             False                 True        False  False    True
4             False                 True        False  False    True
5             False                 True        False  False    True
6             False                 True        False  False    True
7             False                 True        False  False    True
8             False                 True        False  False    True
9             False                 True        False  False    True
10            False                 True        False  False    True
11            False                 True        False  False   False
12            False                 True        False  False    True
13            False                 True        False  False    True
14            False                 True        False  False    True
15            False                 True        False  False    True
16            False                 True        False  False    True
17            False                 True        False  False    True
18            False                 True        False  False    True
19            False                 True        False  False    True

    seller_information  variations  best_offer  more_offers  category
0                False        True       False        False     False
1                False        True       False        False     False
2                False        True       False        False     False
3                False        True       False        False     False
4                False        True       False        False     False
5                False        True       False        False     False
6                False        True       False        False     False
7                False       False       False        False     False
8                False        True       False        False     False
9                False        True       False        False     False
10               False       False       False        False     False
11               False       False       False        False     False
12               False        True       False        False     False
13               False        True       False        False     False
14               False        True       False        False     False
15               False        True       False        False     False
16               False        True       False        False     False
17               False        True       False        False     False
18               False        True       False        False     False
19               False        True       False        False     False

[20 rows x 24 columns]

In [12]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       20
seller_name                0
sizes                      0
videos                    19
seller_information         0
variations                17
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [13]:
df["what_customers_said"] = df["what_customers_said"].astype(str)
df["what_customers_said"]

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
Name: what_customers_said, dtype: str

In [20]:
df["what_customers_said" ] = df["what_customers_said"].fillna("Good Product")
df[["what_customers_said"]]

   what_customers_said
0         good Product
1         good Product
2         good Product
3         good Product
4         good Product
5         good Product
6         good Product
7         good Product
8         good Product
9         good Product
10        good Product
11        good Product
12        good Product
13        good Product
14        good Product
15        good Product
16        good Product
17        good Product
18        good Product
19        good Product

In [22]:
df["videos"] = df["videos"].fillna("Unknown")
df["videos"]

0                    Unknown
1                    Unknown
2                    Unknown
3                    Unknown
4                    Unknown
5                    Unknown
6                    Unknown
7                    Unknown
8                    Unknown
9                    Unknown
10                   Unknown
11    ["rw-19990734_cae700"]
12                   Unknown
13                   Unknown
14                   Unknown
15                   Unknown
16                   Unknown
17                   Unknown
18                   Unknown
19                   Unknown
Name: videos, dtype: str

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              20 non-null     int64
 1   title                   20 non-null     str
 2   product_description     20 non-null     str
 3   rating                  20 non-null     float64
 4   ratings_count           20 non-null     int64
 5   initial_price           20 non-null     float64
 6   discount                20 non-null     float64
 7   final_price             20 non-null     str
 8   currency                20 non-null     str
 9   images                  20 non-null     str
 10  delivery_options        20 non-null     str
 11  product_details         20 non-null     str
 12  breadcrumbs             20 non-null     str
 13  product_specifications  20 non-null     str
 14  amount_of_stars         20 non-null     str
 15  what_customers_said     20 non-null     str
 16  seller_name             20 non-null     str
 17  sizes                   20 non-null     str
 18  videos                  20 non-null     str
 19  seller_information      20 non-null     str
 20  variations              3 non-null      str
 21  best_offer              20 non-null     str
 22  more_offers             20 non-null     str
 23  category                20 non-null     str
dtypes: float64(3), int64(2), str(19)
memory usage: 3.9 KB

In [24]:
df[["variations"]]

          variations
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
5                NaN
6                NaN
7            [{},{}]
8                NaN
9                NaN
10              [{}]
11  [{},{},{},{},{}]
12               NaN
13               NaN
14               NaN
15               NaN
16               NaN
17               NaN
18               NaN
19               NaN

In [26]:
df["variations"] = df["variations"].fillna("[{}]")
df["variations"]

0                 [{}]
1                 [{}]
2                 [{}]
3                 [{}]
4                 [{}]
5                 [{}]
6                 [{}]
7              [{},{}]
8                 [{}]
9                 [{}]
10                [{}]
11    [{},{},{},{},{}]
12                [{}]
13                [{}]
14                [{}]
15                [{}]
16                [{}]
17                [{}]
18                [{}]
19                [{}]
Name: variations, dtype: str

Basic Operations

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              20 non-null     int64
 1   title                   20 non-null     str
 2   product_description     20 non-null     str
 3   rating                  20 non-null     float64
 4   ratings_count           20 non-null     int64
 5   initial_price           20 non-null     float64
 6   discount                20 non-null     float64
 7   final_price             20 non-null     str
 8   currency                20 non-null     str
 9   images                  20 non-null     str
 10  delivery_options        20 non-null     str
 11  product_details         20 non-null     str
 12  breadcrumbs             20 non-null     str
 13  product_specifications  20 non-null     str
 14  amount_of_stars         20 non-null     str
 15  what_customers_said     20 non-null     str
 16  seller_name             20 non-null     str
 17  sizes                   20 non-null     str
 18  videos                  20 non-null     str
 19  seller_information      20 non-null     str
 20  variations              20 non-null     str
 21  best_offer              20 non-null     str
 22  more_offers             20 non-null     str
 23  category                20 non-null     str
dtypes: float64(3), int64(2), str(19)
memory usage: 3.9 KB

In [28]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21604464,Inddus,Pink Sheer Floral Embroidered Midi Ethnic Dres...,3.3,7,6299.0,58.0,"""₹2,645.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Nat███l L███sty█████████ts ██████████████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,4-B███nja███Tow█████████oin███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
1,21990058,Rustorange,Floral Printed A-Line Midi Ethnic Dress,5.0,2,3299.0,55.0,"""₹1,484.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Zak███i I███tec█████████ Li██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",Unknown,1st███oor███ - █████████R -███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
2,21992820,PANIT,Embroidered Sequinned Georgette Fit And Flare ...,4.4,14,7999.0,71.0,"""₹2,319.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",good Product,R.U███NGH███D G█████████PPA█████████████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,G-6███Gro███ fl█████████-6N███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
3,15741084,Ashnaina,Red Floral Crepe Tiered Maxi Dress,3.2,6,1799.0,65.0,"""₹629.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",good Product,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-1███ OK███ IN█████████ASE███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
4,15741088,Ashnaina,Women Brown Animal Midi Fit and Flare Dress,4.1,88,1799.0,67.0,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":12,""4_stars""...",good Product,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-1███ OK███ IN█████████ASE███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
5,15788632,AURELIA,Black Checked Empire Midi Dress,4.2,14,2499.0,44.0,"""₹1,380.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",good Product,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
6,15749780,W,Women Mustard Yellow & White Ethnic Printed Ma...,4.3,23,3999.0,60.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,Fla███ech███tai███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,"3rd███165███th █████████, s███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
7,16197802,Vishudh,Grey Floral Embroidered Ethnic Maxi Dress,3.9,609,3049.0,60.0,"""₹853.00""",INR,http://assets.myntassets.com/assets/images/161...,...,"{""1_star"":77,""2_stars"":36,""3_stars"":56,""4_star...",good Product,Fla███tar███mme██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,"1st███oor███abi█████████02,███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
8,19197596,W,Blue Floral Chiffon A-Line Midi Dress,3.9,10,2799.0,49.0,"""₹1,420.00""",INR,http://assets.myntassets.com/assets/images/191...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",good Product,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
9,18922226,Ahalyaa,Off White Geometric Printed Maxi Dress,2.8,8,4300.0,63.0,"""₹1,591.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":3,""4_stars"":...",good Product,UDA███ASH███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,1ST███OOR███D 2█████████ PL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
10,22411344,Juniper,Floral Embroidered Flared Cotton Midi Dress,3.9,11,4149.0,75.0,"""₹1,037.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",good Product,AMA███XPO███ IN█████████AL █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""To...",Unknown,G-9███SIT███RA █████████L A███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
11,19990734,VASTRAMAY,Girls Mustard Yellow Chikankari Cotton Ethnic ...,4.7,9,2499.0,61.0,"""₹974.00""",INR,http://assets.myntassets.com/assets/images/199...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Vas███may███t. ██████,"[{""size"":""2-3Y"",""value"":""9.5in"",""value_name"":""...","[""rw-19990734_cae700""]",59A███ATH███AR █████████Kol███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
12,10127829,Geroo Jaipur,White & Red Floral Hand Block Printed Pure Cot...,3.8,6,2499.0,60.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,ITS███FFE███T,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""T...",Unknown,21-███gal███har█████████l P███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
13,10132319,Karmic Vision,Women Grey & Red Solid Maxi Dress,3.9,12,4999.0,53.0,"""₹2,349.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",good Product,V S███ERS███,"[{""size"":""S"",""value"":""34.5in"",""value_name"":""To...",Unknown,F-6███Ary███ama█████████hi ██████████████████,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
14,13404948,YASH GALLERY,Women Black & White Cotton Printed A-Line Mate...,4.1,67,3899.0,76.0,"""₹935.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":5,""3_stars"":8,""4_stars"":...",good Product,Yas███all███ Pr█████████ite███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-6███RO.███. 6█████████SIK███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
15,12994772,Souchii,Women Cream-Coloured Floral Printed A-Line Dress,3.9,10,1999.0,47.0,"""₹1,059.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",good Product,MOH███BHO███AMU█████████ATE█████████,"[{""size"":""S"",""value"":""42.0in"",""value_name"":""Fr...",Unknown,"no-███, G███ama█████████, b███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
16,13355452,Rangriti,Women Coral Pink & White Liva Checked A-Line D...,4.4,33,1299.0,35.0,"""₹1,299.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":3,""4_stars"":...",good Product,Sup███om ███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Fr...",Unknown,Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
17,13405888,Saanjh,Women Green Printed Fit and Flare Dress,4.0,7,1969.0,62.0,"""₹787.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,SHA███ RE███LS,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,C 5███ RR███NEX█████████BEH███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
18,22603284,JAIPURI COLLECTION,Ethnic Motifs Printed Maxi Ethnic Dress,3.9,10,2899.0,71.0,"""₹840.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Jai███i C███ect██████,"[{""size"":""M"",""value"":""52.0in"",""value_name"":""Fr...",Unknown,"46,███ini███lon█████████erJ███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
19,22583702,Mialo fashion,Ethnic Printed Kaftan Dress,2.7,9,2999.0,78.0,"""₹659.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":1,""4_stars"":...",good Product,MIA███FAS███N,"[{""size"":""S"",""value"":""46.0in"",""value_name"":""Fr...",Unknown,11/███ Ka███i P█████████aro███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses

1. Select Columns

In [29]:
df[["product_id", "title", "final_price"]]

    product_id               title  final_price
0     21604464              Inddus  "₹2,645.00"
1     21990058          Rustorange  "₹1,484.00"
2     21992820               PANIT  "₹2,319.00"
3     15741084            Ashnaina    "₹629.00"
4     15741088            Ashnaina    "₹593.00"
5     15788632             AURELIA  "₹1,380.00"
6     15749780                   W  "₹1,599.00"
7     16197802             Vishudh    "₹853.00"
8     19197596                   W  "₹1,420.00"
9     18922226             Ahalyaa  "₹1,591.00"
10    22411344             Juniper  "₹1,037.00"
11    19990734           VASTRAMAY    "₹974.00"
12    10127829        Geroo Jaipur    "₹999.00"
13    10132319       Karmic Vision  "₹2,349.00"
14    13404948        YASH GALLERY    "₹935.00"
15    12994772             Souchii  "₹1,059.00"
16    13355452            Rangriti  "₹1,299.00"
17    13405888              Saanjh    "₹787.00"
18    22603284  JAIPURI COLLECTION    "₹840.00"
19    22583702       Mialo fashion    "₹659.00"

In [30]:
df[["product_id", "title", "product_description", "rating"]]

,product_id,title,product_description,rating
0,21604464,Inddus,Pink Sheer Floral Embroidered Midi Ethnic Dres...,3.3
1,21990058,Rustorange,Floral Printed A-Line Midi Ethnic Dress,5.0
2,21992820,PANIT,Embroidered Sequinned Georgette Fit And Flare ...,4.4
3,15741084,Ashnaina,Red Floral Crepe Tiered Maxi Dress,3.2
4,15741088,Ashnaina,Women Brown Animal Midi Fit and Flare Dress,4.1
5,15788632,AURELIA,Black Checked Empire Midi Dress,4.2
6,15749780,W,Women Mustard Yellow & White Ethnic Printed Ma...,4.3
7,16197802,Vishudh,Grey Floral Embroidered Ethnic Maxi Dress,3.9
8,19197596,W,Blue Floral Chiffon A-Line Midi Dress,3.9
9,18922226,Ahalyaa,Off White Geometric Printed Maxi Dress,2.8
10,22411344,Juniper,Floral Embroidered Flared Cotton Midi Dress,3.9
11,19990734,VASTRAMAY,Girls Mustard Yellow Chikankari Cotton Ethnic ...,4.7
12,10127829,Geroo Jaipur,White & Red Floral Hand Block Printed Pure Cot...,3.8
13,10132319,Karmic Vision,Women Grey & Red Solid Maxi Dress,3.9
14,13404948,YASH GALLERY,Women Black & White Cotton Printed A-Line Mate...,4.1
15,12994772,Souchii,Women Cream-Coloured Floral Printed A-Line Dress,3.9
16,13355452,Rangriti,Women Coral Pink & White Liva Checked A-Line D...,4.4
17,13405888,Saanjh,Women Green Printed Fit and Flare Dress,4.0
18,22603284,JAIPURI COLLECTION,Ethnic Motifs Printed Maxi Ethnic Dress,3.9
19,22583702,Mialo fashion,Ethnic Printed Kaftan Dress,2.7

2. Filter rows

In [31]:
df[df["rating"] >= 4.0]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,21990058,Rustorange,Floral Printed A-Line Midi Ethnic Dress,5.0,2,3299.0,55.0,"""₹1,484.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Zak███i I███tec█████████ Li██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",Unknown,1st███oor███ - █████████R -███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
2,21992820,PANIT,Embroidered Sequinned Georgette Fit And Flare ...,4.4,14,7999.0,71.0,"""₹2,319.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",good Product,R.U███NGH███D G█████████PPA█████████████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,G-6███Gro███ fl█████████-6N███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
4,15741088,Ashnaina,Women Brown Animal Midi Fit and Flare Dress,4.1,88,1799.0,67.0,"""₹593.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":12,""4_stars""...",good Product,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-1███ OK███ IN█████████ASE███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
5,15788632,AURELIA,Black Checked Empire Midi Dress,4.2,14,2499.0,44.0,"""₹1,380.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",good Product,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
6,15749780,W,Women Mustard Yellow & White Ethnic Printed Ma...,4.3,23,3999.0,60.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,Fla███ech███tai███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,"3rd███165███th █████████, s███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
11,19990734,VASTRAMAY,Girls Mustard Yellow Chikankari Cotton Ethnic ...,4.7,9,2499.0,61.0,"""₹974.00""",INR,http://assets.myntassets.com/assets/images/199...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Vas███may███t. ██████,"[{""size"":""2-3Y"",""value"":""9.5in"",""value_name"":""...","[""rw-19990734_cae700""]",59A███ATH███AR █████████Kol███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
14,13404948,YASH GALLERY,Women Black & White Cotton Printed A-Line Mate...,4.1,67,3899.0,76.0,"""₹935.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":5,""3_stars"":8,""4_stars"":...",good Product,Yas███all███ Pr█████████ite███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-6███RO.███. 6█████████SIK███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
16,13355452,Rangriti,Women Coral Pink & White Liva Checked A-Line D...,4.4,33,1299.0,35.0,"""₹1,299.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":3,""4_stars"":...",good Product,Sup███om ███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Fr...",Unknown,Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
17,13405888,Saanjh,Women Green Printed Fit and Flare Dress,4.0,7,1969.0,62.0,"""₹787.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,SHA███ RE███LS,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,C 5███ RR███NEX█████████BEH███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses

In [32]:
df[(df["rating"] > 2.5) & (df["rating"] <= 4.0)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21604464,Inddus,Pink Sheer Floral Embroidered Midi Ethnic Dres...,3.3,7,6299.0,58.0,"""₹2,645.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Nat███l L███sty█████████ts ██████████████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,4-B███nja███Tow█████████oin███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
3,15741084,Ashnaina,Red Floral Crepe Tiered Maxi Dress,3.2,6,1799.0,65.0,"""₹629.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",good Product,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-1███ OK███ IN█████████ASE███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
7,16197802,Vishudh,Grey Floral Embroidered Ethnic Maxi Dress,3.9,609,3049.0,60.0,"""₹853.00""",INR,http://assets.myntassets.com/assets/images/161...,...,"{""1_star"":77,""2_stars"":36,""3_stars"":56,""4_star...",good Product,Fla███tar███mme██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,"1st███oor███abi█████████02,███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
8,19197596,W,Blue Floral Chiffon A-Line Midi Dress,3.9,10,2799.0,49.0,"""₹1,420.00""",INR,http://assets.myntassets.com/assets/images/191...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",good Product,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
9,18922226,Ahalyaa,Off White Geometric Printed Maxi Dress,2.8,8,4300.0,63.0,"""₹1,591.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":3,""4_stars"":...",good Product,UDA███ASH███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,1ST███OOR███D 2█████████ PL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
10,22411344,Juniper,Floral Embroidered Flared Cotton Midi Dress,3.9,11,4149.0,75.0,"""₹1,037.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",good Product,AMA███XPO███ IN█████████AL █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""To...",Unknown,G-9███SIT███RA █████████L A███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
12,10127829,Geroo Jaipur,White & Red Floral Hand Block Printed Pure Cot...,3.8,6,2499.0,60.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,ITS███FFE███T,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""T...",Unknown,21-███gal███har█████████l P███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
13,10132319,Karmic Vision,Women Grey & Red Solid Maxi Dress,3.9,12,4999.0,53.0,"""₹2,349.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",good Product,V S███ERS███,"[{""size"":""S"",""value"":""34.5in"",""value_name"":""To...",Unknown,F-6███Ary███ama█████████hi ██████████████████,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
15,12994772,Souchii,Women Cream-Coloured Floral Printed A-Line Dress,3.9,10,1999.0,47.0,"""₹1,059.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",good Product,MOH███BHO███AMU█████████ATE█████████,"[{""size"":""S"",""value"":""42.0in"",""value_name"":""Fr...",Unknown,"no-███, G███ama█████████, b███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
17,13405888,Saanjh,Women Green Printed Fit and Flare Dress,4.0,7,1969.0,62.0,"""₹787.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,SHA███ RE███LS,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,C 5███ RR███NEX█████████BEH███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
18,22603284,JAIPURI COLLECTION,Ethnic Motifs Printed Maxi Ethnic Dress,3.9,10,2899.0,71.0,"""₹840.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Jai███i C███ect██████,"[{""size"":""M"",""value"":""52.0in"",""value_name"":""Fr...",Unknown,"46,███ini███lon█████████erJ███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
19,22583702,Mialo fashion,Ethnic Printed Kaftan Dress,2.7,9,2999.0,78.0,"""₹659.00""",INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":1,""4_stars"":...",good Product,MIA███FAS███N,"[{""size"":""S"",""value"":""46.0in"",""value_name"":""Fr...",Unknown,11/███ Ka███i P█████████aro███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses

In [33]:
df[["final_price"]]

    final_price
0   "₹2,645.00"
1   "₹1,484.00"
2   "₹2,319.00"
3     "₹629.00"
4     "₹593.00"
5   "₹1,380.00"
6   "₹1,599.00"
7     "₹853.00"
8   "₹1,420.00"
9   "₹1,591.00"
10  "₹1,037.00"
11    "₹974.00"
12    "₹999.00"
13  "₹2,349.00"
14    "₹935.00"
15  "₹1,059.00"
16  "₹1,299.00"
17    "₹787.00"
18    "₹840.00"
19    "₹659.00"

In [34]:
df["final_price"] = df["final_price"].str.replace("₹", "")
df["final_price"] = df["final_price"].str.replace(",", "")
df["final_price"]

0     "2645.00"
1     "1484.00"
2     "2319.00"
3      "629.00"
4      "593.00"
5     "1380.00"
6     "1599.00"
7      "853.00"
8     "1420.00"
9     "1591.00"
10    "1037.00"
11     "974.00"
12     "999.00"
13    "2349.00"
14     "935.00"
15    "1059.00"
16    "1299.00"
17     "787.00"
18     "840.00"
19     "659.00"
Name: final_price, dtype: str

In [35]:
df["final_price"] = df["final_price"].str.replace('"', "")
df["final_price"]

0     2645.00
1     1484.00
2     2319.00
3      629.00
4      593.00
5     1380.00
6     1599.00
7      853.00
8     1420.00
9     1591.00
10    1037.00
11     974.00
12     999.00
13    2349.00
14     935.00
15    1059.00
16    1299.00
17     787.00
18     840.00
19     659.00
Name: final_price, dtype: str

In [36]:
df["final_price"] = df['final_price'].astype(float)

In [37]:
df["final_price"]

0     2645.0
1     1484.0
2     2319.0
3      629.0
4      593.0
5     1380.0
6     1599.0
7      853.0
8     1420.0
9     1591.0
10    1037.0
11     974.0
12     999.0
13    2349.0
14     935.0
15    1059.0
16    1299.0
17     787.0
18     840.0
19     659.0
Name: final_price, dtype: float64

In [38]:
df[df["final_price"] > 1500.0]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21604464,Inddus,Pink Sheer Floral Embroidered Midi Ethnic Dres...,3.3,7,6299.0,58.0,2645.0,INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Nat███l L███sty█████████ts ██████████████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,4-B███nja███Tow█████████oin███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
2,21992820,PANIT,Embroidered Sequinned Georgette Fit And Flare ...,4.4,14,7999.0,71.0,2319.0,INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",good Product,R.U███NGH███D G█████████PPA█████████████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,G-6███Gro███ fl█████████-6N███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
6,15749780,W,Women Mustard Yellow & White Ethnic Printed Ma...,4.3,23,3999.0,60.0,1599.0,INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,Fla███ech███tai███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,"3rd███165███th █████████, s███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
9,18922226,Ahalyaa,Off White Geometric Printed Maxi Dress,2.8,8,4300.0,63.0,1591.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":3,""4_stars"":...",good Product,UDA███ASH███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,1ST███OOR███D 2█████████ PL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
13,10132319,Karmic Vision,Women Grey & Red Solid Maxi Dress,3.9,12,4999.0,53.0,2349.0,INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",good Product,V S███ERS███,"[{""size"":""S"",""value"":""34.5in"",""value_name"":""To...",Unknown,F-6███Ary███ama█████████hi ██████████████████,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses

Remove Duplicates

In [39]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,21604464,Inddus,Pink Sheer Floral Embroidered Midi Ethnic Dres...,3.3,7,6299.0,58.0,2645.0,INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Nat███l L███sty█████████ts ██████████████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,4-B███nja███Tow█████████oin███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
1,21990058,Rustorange,Floral Printed A-Line Midi Ethnic Dress,5.0,2,3299.0,55.0,1484.0,INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Zak███i I███tec█████████ Li██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",Unknown,1st███oor███ - █████████R -███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
2,21992820,PANIT,Embroidered Sequinned Georgette Fit And Flare ...,4.4,14,7999.0,71.0,2319.0,INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":0,""2_stars"":2,""3_stars"":1,""4_stars"":...",good Product,R.U███NGH███D G█████████PPA█████████████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,G-6███Gro███ fl█████████-6N███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
3,15741084,Ashnaina,Red Floral Crepe Tiered Maxi Dress,3.2,6,1799.0,65.0,629.0,INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",good Product,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-1███ OK███ IN█████████ASE███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
4,15741088,Ashnaina,Women Brown Animal Midi Fit and Flare Dress,4.1,88,1799.0,67.0,593.0,INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":7,""2_stars"":3,""3_stars"":12,""4_stars""...",good Product,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-1███ OK███ IN█████████ASE███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
5,15788632,AURELIA,Black Checked Empire Midi Dress,4.2,14,2499.0,44.0,1380.0,INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",good Product,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
6,15749780,W,Women Mustard Yellow & White Ethnic Printed Ma...,4.3,23,3999.0,60.0,1599.0,INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,Fla███ech███tai███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,"3rd███165███th █████████, s███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
7,16197802,Vishudh,Grey Floral Embroidered Ethnic Maxi Dress,3.9,609,3049.0,60.0,853.0,INR,http://assets.myntassets.com/assets/images/161...,...,"{""1_star"":77,""2_stars"":36,""3_stars"":56,""4_star...",good Product,Fla███tar███mme██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,"1st███oor███abi█████████02,███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
8,19197596,W,Blue Floral Chiffon A-Line Midi Dress,3.9,10,2799.0,49.0,1420.0,INR,http://assets.myntassets.com/assets/images/191...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",good Product,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
9,18922226,Ahalyaa,Off White Geometric Printed Maxi Dress,2.8,8,4300.0,63.0,1591.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":3,""4_stars"":...",good Product,UDA███ASH███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,1ST███OOR███D 2█████████ PL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
10,22411344,Juniper,Floral Embroidered Flared Cotton Midi Dress,3.9,11,4149.0,75.0,1037.0,INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",good Product,AMA███XPO███ IN█████████AL █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""To...",Unknown,G-9███SIT███RA █████████L A███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
11,19990734,VASTRAMAY,Girls Mustard Yellow Chikankari Cotton Ethnic ...,4.7,9,2499.0,61.0,974.0,INR,http://assets.myntassets.com/assets/images/199...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Vas███may███t. ██████,"[{""size"":""2-3Y"",""value"":""9.5in"",""value_name"":""...","[""rw-19990734_cae700""]",59A███ATH███AR █████████Kol███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
12,10127829,Geroo Jaipur,White & Red Floral Hand Block Printed Pure Cot...,3.8,6,2499.0,60.0,999.0,INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,ITS███FFE███T,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""T...",Unknown,21-███gal███har█████████l P███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
13,10132319,Karmic Vision,Women Grey & Red Solid Maxi Dress,3.9,12,4999.0,53.0,2349.0,INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":2,""4_stars"":...",good Product,V S███ERS███,"[{""size"":""S"",""value"":""34.5in"",""value_name"":""To...",Unknown,F-6███Ary███ama█████████hi ██████████████████,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
14,13404948,YASH GALLERY,Women Black & White Cotton Printed A-Line Mate...,4.1,67,3899.0,76.0,935.0,INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":5,""3_stars"":8,""4_stars"":...",good Product,Yas███all███ Pr█████████ite███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-6███RO.███. 6█████████SIK███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
15,12994772,Souchii,Women Cream-Coloured Floral Printed A-Line Dress,3.9,10,1999.0,47.0,1059.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...",good Product,MOH███BHO███AMU█████████ATE█████████,"[{""size"":""S"",""value"":""42.0in"",""value_name"":""Fr...",Unknown,"no-███, G███ama█████████, b███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
16,13355452,Rangriti,Women Coral Pink & White Liva Checked A-Line D...,4.4,33,1299.0,35.0,1299.0,INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":3,""4_stars"":...",good Product,Sup███om ███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Fr...",Unknown,Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
17,13405888,Saanjh,Women Green Printed Fit and Flare Dress,4.0,7,1969.0,62.0,787.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",good Product,SHA███ RE███LS,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,C 5███ RR███NEX█████████BEH███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
18,22603284,JAIPURI COLLECTION,Ethnic Motifs Printed Maxi Ethnic Dress,3.9,10,2899.0,71.0,840.0,INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",good Product,Jai███i C███ect██████,"[{""size"":""M"",""value"":""52.0in"",""value_name"":""Fr...",Unknown,"46,███ini███lon█████████erJ███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
19,22583702,Mialo fashion,Ethnic Printed Kaftan Dress,2.7,9,2999.0,78.0,659.0,INR,http://assets.myntassets.com/assets/images/225...,...,"{""1_star"":4,""2_stars"":1,""3_stars"":1,""4_stars"":...",good Product,MIA███FAS███N,"[{""size"":""S"",""value"":""46.0in"",""value_name"":""Fr...",Unknown,11/███ Ka███i P█████████aro███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses

In [40]:
df.duplicated().sum()

np.int64(0)

No duplicates found

Creating a Derived column

In [41]:
df["quantity"] = 2;
df["total_amount"] = df["final_price"] * df["quantity"]
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,21604464,Inddus,Pink Sheer Floral Embroidered Midi Ethnic Dres...,3.3,7,6299.0,58.0,2645.0,INR,http://assets.myntassets.com/assets/images/216...,...,Nat███l L███sty█████████ts ██████████████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,4-B███nja███Tow█████████oin███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,5290.0
1,21990058,Rustorange,Floral Printed A-Line Midi Ethnic Dress,5.0,2,3299.0,55.0,1484.0,INR,http://assets.myntassets.com/assets/images/219...,...,Zak███i I███tec█████████ Li██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",Unknown,1st███oor███ - █████████R -███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2968.0
2,21992820,PANIT,Embroidered Sequinned Georgette Fit And Flare ...,4.4,14,7999.0,71.0,2319.0,INR,http://assets.myntassets.com/assets/images/219...,...,R.U███NGH███D G█████████PPA█████████████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,G-6███Gro███ fl█████████-6N███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,4638.0
3,15741084,Ashnaina,Red Floral Crepe Tiered Maxi Dress,3.2,6,1799.0,65.0,629.0,INR,http://assets.myntassets.com/assets/images/157...,...,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-1███ OK███ IN█████████ASE███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1258.0
4,15741088,Ashnaina,Women Brown Animal Midi Fit and Flare Dress,4.1,88,1799.0,67.0,593.0,INR,http://assets.myntassets.com/assets/images/157...,...,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-1███ OK███ IN█████████ASE███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1186.0
5,15788632,AURELIA,Black Checked Empire Midi Dress,4.2,14,2499.0,44.0,1380.0,INR,http://assets.myntassets.com/assets/images/157...,...,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2760.0
6,15749780,W,Women Mustard Yellow & White Ethnic Printed Ma...,4.3,23,3999.0,60.0,1599.0,INR,http://assets.myntassets.com/assets/images/157...,...,Fla███ech███tai███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,"3rd███165███th █████████, s███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,3198.0
7,16197802,Vishudh,Grey Floral Embroidered Ethnic Maxi Dress,3.9,609,3049.0,60.0,853.0,INR,http://assets.myntassets.com/assets/images/161...,...,Fla███tar███mme██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,"1st███oor███abi█████████02,███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1706.0
8,19197596,W,Blue Floral Chiffon A-Line Midi Dress,3.9,10,2799.0,49.0,1420.0,INR,http://assets.myntassets.com/assets/images/191...,...,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2840.0
9,18922226,Ahalyaa,Off White Geometric Printed Maxi Dress,2.8,8,4300.0,63.0,1591.0,INR,http://assets.myntassets.com/assets/images/189...,...,UDA███ASH███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,1ST███OOR███D 2█████████ PL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,3182.0
10,22411344,Juniper,Floral Embroidered Flared Cotton Midi Dress,3.9,11,4149.0,75.0,1037.0,INR,http://assets.myntassets.com/assets/images/224...,...,AMA███XPO███ IN█████████AL █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""To...",Unknown,G-9███SIT███RA █████████L A███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2074.0
11,19990734,VASTRAMAY,Girls Mustard Yellow Chikankari Cotton Ethnic ...,4.7,9,2499.0,61.0,974.0,INR,http://assets.myntassets.com/assets/images/199...,...,Vas███may███t. ██████,"[{""size"":""2-3Y"",""value"":""9.5in"",""value_name"":""...","[""rw-19990734_cae700""]",59A███ATH███AR █████████Kol███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1948.0
12,10127829,Geroo Jaipur,White & Red Floral Hand Block Printed Pure Cot...,3.8,6,2499.0,60.0,999.0,INR,http://assets.myntassets.com/assets/images/101...,...,ITS███FFE███T,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""T...",Unknown,21-███gal███har█████████l P███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1998.0
13,10132319,Karmic Vision,Women Grey & Red Solid Maxi Dress,3.9,12,4999.0,53.0,2349.0,INR,http://assets.myntassets.com/assets/images/101...,...,V S███ERS███,"[{""size"":""S"",""value"":""34.5in"",""value_name"":""To...",Unknown,F-6███Ary███ama█████████hi ██████████████████,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,4698.0
14,13404948,YASH GALLERY,Women Black & White Cotton Printed A-Line Mate...,4.1,67,3899.0,76.0,935.0,INR,http://assets.myntassets.com/assets/images/134...,...,Yas███all███ Pr█████████ite███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-6███RO.███. 6█████████SIK███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1870.0
15,12994772,Souchii,Women Cream-Coloured Floral Printed A-Line Dress,3.9,10,1999.0,47.0,1059.0,INR,http://assets.myntassets.com/assets/images/pro...,...,MOH███BHO███AMU█████████ATE█████████,"[{""size"":""S"",""value"":""42.0in"",""value_name"":""Fr...",Unknown,"no-███, G███ama█████████, b███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2118.0
16,13355452,Rangriti,Women Coral Pink & White Liva Checked A-Line D...,4.4,33,1299.0,35.0,1299.0,INR,http://assets.myntassets.com/assets/images/133...,...,Sup███om ███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Fr...",Unknown,Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2598.0
17,13405888,Saanjh,Women Green Printed Fit and Flare Dress,4.0,7,1969.0,62.0,787.0,INR,http://assets.myntassets.com/assets/images/pro...,...,SHA███ RE███LS,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,C 5███ RR███NEX█████████BEH███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1574.0
18,22603284,JAIPURI COLLECTION,Ethnic Motifs Printed Maxi Ethnic Dress,3.9,10,2899.0,71.0,840.0,INR,http://assets.myntassets.com/assets/images/226...,...,Jai███i C███ect██████,"[{""size"":""M"",""value"":""52.0in"",""value_name"":""Fr...",Unknown,"46,███ini███lon█████████erJ███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1680.0
19,22583702,Mialo fashion,Ethnic Printed Kaftan Dress,2.7,9,2999.0,78.0,659.0,INR,http://assets.myntassets.com/assets/images/225...,...,MIA███FAS███N,"[{""size"":""S"",""value"":""46.0in"",""value_name"":""Fr...",Unknown,11/███ Ka███i P█████████aro███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1318.0

In [42]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,21604464,Inddus,Pink Sheer Floral Embroidered Midi Ethnic Dres...,3.3,7,6299.0,58.0,2645.0,INR,http://assets.myntassets.com/assets/images/216...,...,Nat███l L███sty█████████ts ██████████████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,4-B███nja███Tow█████████oin███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,5290.0
1,21990058,Rustorange,Floral Printed A-Line Midi Ethnic Dress,5.0,2,3299.0,55.0,1484.0,INR,http://assets.myntassets.com/assets/images/219...,...,Zak███i I███tec█████████ Li██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",Unknown,1st███oor███ - █████████R -███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2968.0
2,21992820,PANIT,Embroidered Sequinned Georgette Fit And Flare ...,4.4,14,7999.0,71.0,2319.0,INR,http://assets.myntassets.com/assets/images/219...,...,R.U███NGH███D G█████████PPA█████████████████████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,G-6███Gro███ fl█████████-6N███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,4638.0
3,15741084,Ashnaina,Red Floral Crepe Tiered Maxi Dress,3.2,6,1799.0,65.0,629.0,INR,http://assets.myntassets.com/assets/images/157...,...,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-1███ OK███ IN█████████ASE███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1258.0
4,15741088,Ashnaina,Women Brown Animal Midi Fit and Flare Dress,4.1,88,1799.0,67.0,593.0,INR,http://assets.myntassets.com/assets/images/157...,...,WWC███ON ███LER███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-1███ OK███ IN█████████ASE███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1186.0
5,15788632,AURELIA,Black Checked Empire Midi Dress,4.2,14,2499.0,44.0,1380.0,INR,http://assets.myntassets.com/assets/images/157...,...,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2760.0
6,15749780,W,Women Mustard Yellow & White Ethnic Printed Ma...,4.3,23,3999.0,60.0,1599.0,INR,http://assets.myntassets.com/assets/images/157...,...,Fla███ech███tai███,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,"3rd███165███th █████████, s███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,3198.0
7,16197802,Vishudh,Grey Floral Embroidered Ethnic Maxi Dress,3.9,609,3049.0,60.0,853.0,INR,http://assets.myntassets.com/assets/images/161...,...,Fla███tar███mme██████,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,"1st███oor███abi█████████02,███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1706.0
8,19197596,W,Blue Floral Chiffon A-Line Midi Dress,3.9,10,2799.0,49.0,1420.0,INR,http://assets.myntassets.com/assets/images/191...,...,Esh███ox ███mme█████████td,"[{""size"":""XS"",""value"":""31.0in"",""value_name"":""T...",Unknown,Vil███e B███a B█████████ata███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2840.0
9,18922226,Ahalyaa,Off White Geometric Printed Maxi Dress,2.8,8,4300.0,63.0,1591.0,INR,http://assets.myntassets.com/assets/images/189...,...,UDA███ASH███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,1ST███OOR███D 2█████████ PL███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,3182.0
10,22411344,Juniper,Floral Embroidered Flared Cotton Midi Dress,3.9,11,4149.0,75.0,1037.0,INR,http://assets.myntassets.com/assets/images/224...,...,AMA███XPO███ IN█████████AL █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""To...",Unknown,G-9███SIT███RA █████████L A███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2074.0
11,19990734,VASTRAMAY,Girls Mustard Yellow Chikankari Cotton Ethnic ...,4.7,9,2499.0,61.0,974.0,INR,http://assets.myntassets.com/assets/images/199...,...,Vas███may███t. ██████,"[{""size"":""2-3Y"",""value"":""9.5in"",""value_name"":""...","[""rw-19990734_cae700""]",59A███ATH███AR █████████Kol███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1948.0
12,10127829,Geroo Jaipur,White & Red Floral Hand Block Printed Pure Cot...,3.8,6,2499.0,60.0,999.0,INR,http://assets.myntassets.com/assets/images/101...,...,ITS███FFE███T,"[{""size"":""XS"",""value"":""35.0in"",""value_name"":""T...",Unknown,21-███gal███har█████████l P███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1998.0
13,10132319,Karmic Vision,Women Grey & Red Solid Maxi Dress,3.9,12,4999.0,53.0,2349.0,INR,http://assets.myntassets.com/assets/images/101...,...,V S███ERS███,"[{""size"":""S"",""value"":""34.5in"",""value_name"":""To...",Unknown,F-6███Ary███ama█████████hi ██████████████████,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,4698.0
14,13404948,YASH GALLERY,Women Black & White Cotton Printed A-Line Mate...,4.1,67,3899.0,76.0,935.0,INR,http://assets.myntassets.com/assets/images/134...,...,Yas███all███ Pr█████████ite███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...",Unknown,B-6███RO.███. 6█████████SIK███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1870.0
15,12994772,Souchii,Women Cream-Coloured Floral Printed A-Line Dress,3.9,10,1999.0,47.0,1059.0,INR,http://assets.myntassets.com/assets/images/pro...,...,MOH███BHO███AMU█████████ATE█████████,"[{""size"":""S"",""value"":""42.0in"",""value_name"":""Fr...",Unknown,"no-███, G███ama█████████, b███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2118.0
16,13355452,Rangriti,Women Coral Pink & White Liva Checked A-Line D...,4.4,33,1299.0,35.0,1299.0,INR,http://assets.myntassets.com/assets/images/133...,...,Sup███om ███,"[{""size"":""S"",""value"":""41.0in"",""value_name"":""Fr...",Unknown,Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,2598.0
17,13405888,Saanjh,Women Green Printed Fit and Flare Dress,4.0,7,1969.0,62.0,787.0,INR,http://assets.myntassets.com/assets/images/pro...,...,SHA███ RE███LS,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",Unknown,C 5███ RR███NEX█████████BEH███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1574.0
18,22603284,JAIPURI COLLECTION,Ethnic Motifs Printed Maxi Ethnic Dress,3.9,10,2899.0,71.0,840.0,INR,http://assets.myntassets.com/assets/images/226...,...,Jai███i C███ect██████,"[{""size"":""M"",""value"":""52.0in"",""value_name"":""Fr...",Unknown,"46,███ini███lon█████████erJ███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1680.0
19,22583702,Mialo fashion,Ethnic Printed Kaftan Dress,2.7,9,2999.0,78.0,659.0,INR,http://assets.myntassets.com/assets/images/225...,...,MIA███FAS███N,"[{""size"":""S"",""value"":""46.0in"",""value_name"":""Fr...",Unknown,11/███ Ka███i P█████████aro███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses,2,1318.0

In [43]:
df.to_csv("ethnic-cleaned-dataset.csv", index=False)